### ISSUE TITLE
PandaSQL won't run inside main()

### ISSUE THREAD

**Issue by j0ma** [yhat/pandasql#53]
Hi there,

I noticed that when I attempt to call pandasql inside <code>main()</code>, the script throws an error, no matter if I use <code>globals()</code> or <code>locals()</code>. I also tried to define `qdf()` outside `main()`, to no avail.

**Code**

```
# encoding=utf-8

# pandasql_test.py

# description:
# test for pandasql functionality
# inside a main() function

# imports
import pandas as pd
import pandasql as psql

# main function
def main():

    # abbreviate pandasql functionality
    qdf = lambda q: psql.sqldf(q, locals())

    # create data
    df = pd.DataFrame({
        'name': ['Joe', 'Bill', 'Bob'],
        'weight': [70, 85, 75]
    })

    q = 'select * from df'
    print qdf(q)

if __name__ == '__main__':
    main()
```

**Error**
<code>pandasql.sqldf.PandaSQLException: (sqlite3.OperationalError) no such table: df [SQL: 'select \* from df']</code>

Thanks in advance for any advice!

**Comment by yatishkumarbn** [comment]
Even i am facing the same issue, i am trying to develop a rest api using python django framework and i see sqldf not working as part of View.py. if same code is run in a script or Ipython notebook it works fine. Further i analysed into sqldf code and found that env dictionary is not having any dataframe values. So it doesn't write the temp table in sqllite://memory/ but later in the code sqldf is trying to read the table which is creating this error ( no such table). let me know if more details required.

**Comment by chandraatjulo** [comment]
is this solved? how to solve this issue? I am experiencing the same issue

**Comment by javadba** [comment]
Experiencing same issue: I had thought that combining the globals() and locals() would work .. but no dice.

**Comment by javadba** [comment]
Is there any fork of this repo that gets some of these glaring bugs fixed?

**Comment by dylanhogg** [comment]
If you leave out the lambda helper function `qdf` and call `psql.sqldf` directly it works within `main()`

`print(psql.sqldf(q, locals()))`

While annoying, at least there is a work around.

**Comment by javadba** [comment]
Thx I did end up doing something like that . It's a really useful library!

**Comment by laxmachine** [comment]
Although, dylanhogg's answer is correct I would not call this a work around because lambdas are functions too.. and have similar behavior to normal functions. 
for example:
```
f5 = lambda q: locals()
print f5('as')
```
this would print only one local variable q
{'q': 'as'}
which means that using a lambda function itself is wrong when needed to apply locally, it is nonsensical.

I came across this issue when someone from work, asked me to fix this bug they were getting. Which makes me wonder a significant number of users for this package are also going to be relatively new to python and would generally be new to these nuances too. I would recommend removing the usage of lambda function from the wiki itself.

**Comment by summerela** [comment]
@dylanhogg is right on this one.. has there been any kind of fix since July of 2017? Thanks!

**Comment by j0ma** [comment]
Seems like @dylanhogg is indeed correct, and the following code works:

```
# imports
import pandas as pd
import pandasql as psql

# main function
def main():

    # create data
    df = pd.DataFrame({
        'name': ['Joe', 'Bill', 'Bob'],
        'weight': [70, 85, 75]
    })

    q = 'select * from df'
    print(psql.sqldf(q, locals()))

if __name__ == '__main__':
    main()
```

The lambda function also fails when using `globals()`, as per [this yhat tutorial](http://blog.yhat.com/posts/pandasql-sql-for-pandas-dataframes.html). (although the tutorial doesn't use main()).

Since a workaround exists, and the remaining problems have to do with lambda functions, and not main() per se, I figured it's best to move that discussion to another issue. With that in mind, I'm going to go ahead and close this issue.

**Comment by rudy-letote** [comment]
@dylanhogg thanks very much,i leave lambda and use “sqldf（sql,locals())”  works，pay attention to not using globals()

**Comment by loscil06** [comment]
This happened to me recently irregardless of using locals() or globals(), what I did was to merge both locals() and globals() and it worked, like this:
`sqldf(sql_string, {**locals(), **globals()})`

**Comment by EzhilkumarMoorthy** [comment]
I tried all the solution here, still i'm getting the same error "no such table".

**Scenario**
I'm running the application inside the main method and reading Postgres DB using pandas.read_sql_query and then applying some lambda function on Pandas DF. After that i'm trying to read pandas df using pandasql which gives me "no such table" error.

**Comment by loscil06** [comment]
> I tried all the solution here, still i'm getting the same error "no such table".
> 
> **Scenario**
> I'm running the application inside the main method and reading Postgres DB using pandas.read_sql_query and then applying some lambda function on Pandas DF. After that i'm trying to read pandas df using pandasql which gives me "no such table" error.

Probably you're calling locals from the class' scope, try making and invoking a public method that accepts locals and globals from the main program's scope.

**Comment by abubelinha** [comment]
Sorry, I am too inexpert to understand the problem at all. Could someone illustrate me?
I found [this tutorial](https://www.datacamp.com/tutorial/how-to-use-sql-in-pandas-using-pandasql-queries) and I am using this function like in that example, since it says "_optional (and rarely useful) parameter that can be either `locals()` or `globals()`_":

```Python
import seaborn as sns # just to use the same sample dataset to create my dataframe
my_df = sns.load_dataset('penguins')
from pandasql import sqldf
print(sqldf('''SELECT species, island FROM my_df LIMIT 5'''))
```
That just works. Am I missing some functionality not passing more than a query to sqldf function?
What is all that `globals()` and `locals()` issue?

I don't really understand the difference of passing them or not.
Can somebody provide a simple example where passing either globals() or locals() would be necessary?

Thanks

**Comment by kelleyrw** [comment]
I've found a workaround for this.  The issue is at what stack frame `globals()` and `locals()` are called from.  If you peer into the `sqldf` function, it is attempting to pull all the data frames from the stack frame from the frame that is called the `sqldf` function (see `sqldf.get_outer_frame_variables()` method).  So, in your example code, the current frame is the `main`, which works correctly.

I wanted to create a wrapper function, but it didn't work unless I took control of the `env` that is passed.  Here is my simple code:

```python
import inspect
from pandasql import sqldf

def pd_sql(query: str, verbose: bool = False) -> pd.DataFrame:
    If verbose:
        print(query)

    calling_frame = inspect.currentframe().f_back
    env = {**calling_frame.f_globals, **calling_frame.f_locals}
    df = sqldf(query, env)
    return df
```

Here, I have to drop back one frame so that the environment (which contains the dataframes) is passed to the method, and now it works as expected:

```python
def test_pd_sql() -> None:
    foo = pd.DataFrame(data={"col1": [1, 2], "col2": [3, 4]})
    print_dataframe(foo)
    result = pd_sql("select * from foo", verbose=True)
    print_dataframe(result)
    assert foo.equals(result)
```

```util/test_pandas.py::test_pd_sql 

============================== 1 passed in 0.44s ===============================
PASSED                                  [100%]
+----+--------+--------+
|    |   col1 |   col2 |
|----+--------+--------|
|  0 |      1 |      3 |
|  1 |      2 |      4 |
+----+--------+--------+
select * from foo
+----+--------+--------+
|    |   col1 |   col2 |
|----+--------+--------|
|  0 |      1 |      3 |
|  1 |      2 |      4 |
+----+--------+--------+
```

I hope this helps.
